-- Create dispute_letters table
CREATE TABLE IF NOT EXISTS public.dispute_letters (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    letter_type TEXT NOT NULL,
    creditor_name TEXT,
    account_number TEXT,
    letter_content TEXT NOT NULL,
    status TEXT DEFAULT 'draft', -- e.g., draft, sent, responded
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.dispute_letters ENABLE ROW LEVEL SECURITY;

-- Trigger to update "updated_at" timestamp
-- (Assuming handle_updated_at function already exists from user_profiles migration)
CREATE TRIGGER on_dispute_letters_updated
BEFORE UPDATE ON public.dispute_letters
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at(); -- Re-use existing function

-- Policies for dispute_letters
CREATE POLICY "Users can view their own dispute letters"
ON public.dispute_letters FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own dispute letters"
ON public.dispute_letters FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own dispute letters"
ON public.dispute_letters FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own dispute letters"
ON public.dispute_letters FOR DELETE
USING (auth.uid() = user_id);

COMMENT ON TABLE public.dispute_letters IS 'Stores dispute letters generated by users.';
