export const OUTREACH_V4_VERSION = '2026-05-17-v4-rebuild'

export const DEFAULT_DAILY_TARGET_SENDS = 50

export function getDailyTargetSends(value = process.env.OUTREACH_V4_DAILY_TARGET) {
  const parsed = Number.parseInt(String(value || ''), 10)
  if (!Number.isFinite(parsed) || parsed <= 0) return DEFAULT_DAILY_TARGET_SENDS
  return Math.min(parsed, 100)
}

export const V4_VERTICALS = [
  {
    id: 'ai_receptionist',
    label: 'AI Receptionist / missed lead capture',
    quota: 8,
    offer: 'AI Receptionist Launch',
    risk: 'low',
    niches: [
      'restoration companies',
      'roofing contractors',
      'HVAC contractors',
      'plumbing contractors',
      'med spas',
      'property management companies',
    ],
  },
  {
    id: 'search_visibility',
    label: 'Search Visibility / ChatGPT visibility',
    quota: 16,
    offer: 'Search Visibility Sprint',
    risk: 'low',
    niches: [
      'marketing agencies',
      'tax preparers',
      'insurance agencies',
      'home remodeling companies',
      'commercial service companies',
    ],
  },
  {
    id: 'dealvault',
    label: 'DealVault / proof records / agreement tracking',
    quota: 8,
    offer: 'DealVault Agreement & Milestone Records',
    risk: 'low',
    niches: [
      'restoration and mitigation companies',
      'construction project management companies',
      'private lending brokers',
      'hard money brokers',
      'staffing agencies',
      'public adjusters',
    ],
  },
  {
    id: 'funding_prep',
    label: 'Funding Prep / business setup',
    quota: 10,
    offer: 'Business Funding Prep',
    risk: 'medium',
    niches: [
      'new businesses',
      'business consultants',
      'tax preparers',
      'bookkeeping services',
      'minority owned businesses',
    ],
  },
  {
    id: 'no_website',
    label: 'Businesses without websites',
    quota: 2,
    offer: 'Website + AI Receptionist Starter',
    risk: 'low',
    niches: [
      'cleaning companies',
      'landscaping companies',
      'barbershops',
      'auto repair shops',
      'small contractors',
    ],
  },
  {
    id: 'weak_website',
    label: 'Weak websites or broken lead capture',
    quota: 2,
    offer: 'Website Upgrade Sprint',
    risk: 'low',
    niches: [
      'roofing contractors',
      'dental clinics',
      'chiropractors',
      'salons',
      'property management companies',
    ],
  },
  {
    id: 'contractors_home_services',
    label: 'Contractors / home services',
    quota: 16,
    offer: 'AI Receptionist + Search Visibility',
    risk: 'low',
    niches: [
      'general contractors',
      'roofing contractors',
      'restoration contractors',
      'home remodeling companies',
      'commercial cleaning companies',
    ],
  },
  {
    id: 'real_estate_partners',
    label: 'Real estate / property / service businesses',
    quota: 28,
    offer: 'Real Estate Partnership Network',
    risk: 'medium',
    niches: [
      'property management companies',
      'real estate investment companies',
      'wholesalers',
      'private lenders',
      'property preservation companies',
    ],
  },
  {
    id: 'distressed_house',
    label: 'Distressed house pipeline / real estate opportunity discovery',
    quota: 0,
    offer: 'Distressed Property Opportunity Review',
    risk: 'high',
    manualReviewOnly: true,
    niches: [
      'vacant property signals',
      'code violation signals',
      'tax delinquency signals',
      'absentee owner signals',
      'pre-foreclosure signals',
      'probate signals',
      'real estate investor partners',
      'contractor partner targets',
    ],
  },
]

export const BUSINESS_MARKETS = [
  { city: 'Milwaukee', state: 'WI', region: 'Midwest', tier: 1 },
  { city: 'Madison', state: 'WI', region: 'Midwest', tier: 2 },
  { city: 'Green Bay', state: 'WI', region: 'Midwest', tier: 2 },
  { city: 'Chicago', state: 'IL', region: 'Midwest', tier: 1 },
  { city: 'Rockford', state: 'IL', region: 'Midwest', tier: 2 },
  { city: 'Indianapolis', state: 'IN', region: 'Midwest', tier: 1 },
  { city: 'Fort Wayne', state: 'IN', region: 'Midwest', tier: 2 },
  { city: 'Detroit', state: 'MI', region: 'Midwest', tier: 1 },
  { city: 'Grand Rapids', state: 'MI', region: 'Midwest', tier: 2 },
  { city: 'Cleveland', state: 'OH', region: 'Midwest', tier: 1 },
  { city: 'Columbus', state: 'OH', region: 'Midwest', tier: 1 },
  { city: 'Cincinnati', state: 'OH', region: 'Midwest', tier: 1 },
  { city: 'Louisville', state: 'KY', region: 'South', tier: 2 },
  { city: 'Nashville', state: 'TN', region: 'South', tier: 1 },
  { city: 'Memphis', state: 'TN', region: 'South', tier: 1 },
  { city: 'Charlotte', state: 'NC', region: 'South', tier: 1 },
  { city: 'Raleigh', state: 'NC', region: 'South', tier: 1 },
  { city: 'Atlanta', state: 'GA', region: 'South', tier: 1 },
  { city: 'Savannah', state: 'GA', region: 'South', tier: 2 },
  { city: 'Jacksonville', state: 'FL', region: 'South', tier: 1 },
  { city: 'Tampa', state: 'FL', region: 'South', tier: 1 },
  { city: 'Orlando', state: 'FL', region: 'South', tier: 1 },
  { city: 'Houston', state: 'TX', region: 'South', tier: 1 },
  { city: 'Dallas', state: 'TX', region: 'South', tier: 1 },
  { city: 'San Antonio', state: 'TX', region: 'South', tier: 1 },
  { city: 'Austin', state: 'TX', region: 'South', tier: 1 },
  { city: 'Phoenix', state: 'AZ', region: 'West', tier: 1 },
  { city: 'Tucson', state: 'AZ', region: 'West', tier: 2 },
  { city: 'Las Vegas', state: 'NV', region: 'West', tier: 1 },
  { city: 'Denver', state: 'CO', region: 'West', tier: 1 },
  { city: 'Sacramento', state: 'CA', region: 'West', tier: 1 },
  { city: 'Fresno', state: 'CA', region: 'West', tier: 2 },
  { city: 'Richmond', state: 'VA', region: 'East', tier: 2 },
  { city: 'Virginia Beach', state: 'VA', region: 'East', tier: 2 },
  { city: 'Philadelphia', state: 'PA', region: 'East', tier: 1 },
  { city: 'Newark', state: 'NJ', region: 'East', tier: 1 },
]

export const DISTRESSED_HOUSE_MARKETS = [
  { city: 'Milwaukee', state: 'WI', region: 'Midwest', signalMix: ['code_violation', 'vacant_property', 'tax_delinquency'] },
  { city: 'Detroit', state: 'MI', region: 'Midwest', signalMix: ['vacant_property', 'code_violation', 'absentee_owner'] },
  { city: 'Cleveland', state: 'OH', region: 'Midwest', signalMix: ['code_violation', 'tax_delinquency', 'vacant_property'] },
  { city: 'Cincinnati', state: 'OH', region: 'Midwest', signalMix: ['code_violation', 'absentee_owner', 'investor_partner'] },
  { city: 'Indianapolis', state: 'IN', region: 'Midwest', signalMix: ['vacant_property', 'investor_partner', 'contractor_partner'] },
  { city: 'Memphis', state: 'TN', region: 'South', signalMix: ['tax_delinquency', 'absentee_owner', 'vacant_property'] },
  { city: 'Birmingham', state: 'AL', region: 'South', signalMix: ['code_violation', 'probate_indicator', 'contractor_partner'] },
  { city: 'Atlanta', state: 'GA', region: 'South', signalMix: ['investor_partner', 'contractor_partner', 'absentee_owner'] },
  { city: 'Jacksonville', state: 'FL', region: 'South', signalMix: ['vacant_property', 'investor_partner', 'property_manager_partner'] },
  { city: 'Houston', state: 'TX', region: 'South', signalMix: ['contractor_partner', 'investor_partner', 'flood_damage_signal'] },
  { city: 'San Antonio', state: 'TX', region: 'South', signalMix: ['absentee_owner', 'code_violation', 'investor_partner'] },
  { city: 'Phoenix', state: 'AZ', region: 'West', signalMix: ['absentee_owner', 'investor_partner', 'property_manager_partner'] },
  { city: 'Las Vegas', state: 'NV', region: 'West', signalMix: ['absentee_owner', 'vacant_property', 'investor_partner'] },
  { city: 'Philadelphia', state: 'PA', region: 'East', signalMix: ['code_violation', 'tax_delinquency', 'vacant_property'] },
  { city: 'Richmond', state: 'VA', region: 'East', signalMix: ['probate_indicator', 'contractor_partner', 'investor_partner'] },
]

export const COMPLIANCE_BLOCKED_PATTERNS = [
  'stop foreclosure',
  'guaranteed cash offer',
  'guaranteed funding',
  'guaranteed ranking',
  'guaranteed ai citation',
  'legal advice',
  'automatic payout enforcement',
  'remove negative items',
]

export const HIGH_RISK_DISTRESSED_SIGNALS = new Set([
  'pre_foreclosure',
  'probate_indicator',
  'tax_delinquency',
  'foreclosure_auction',
])
