import type { LeadOffer } from '@/lib/leads/types'

export const DEFAULT_GOOGLE_PLACES_NICHES = [
  'boutique property management companies',
  'restoration and mitigation companies',
  'public adjusters and insurance claim consultants',
  'residential remodeling companies',
  'design-build remodelers',
  'specialty trade subcontractors',
  'construction draw and rehab contractors',
  'pool builders and outdoor living contractors',
  'low voltage and security integration contractors',
  'real estate joint venture operators',
  'small property management companies',
  'construction project managers',
  'contingent search firms',
  'staffing agencies',
  'marketing agencies with retainers',
  'event production companies',
  'sponsorship activation agencies',
  'commercial cleaning companies',
  'sign installation companies',
  'parking lot striping companies',
  'permit expediting services',
  'owner representative firms',
  'public adjusters',
  'HVAC contractors',
  'roofing subcontractors',
  'plumbing contractors',
  'electricians',
  'landscaping companies',
  'hard money brokers',
  'private lending brokers',
  'merchant services ISO agencies',
  'payroll and PEO brokers',
  'invoice factoring and purchase order finance companies',
  'mortgage brokers',
  'business funding referral partners',
  'equipment finance brokers',
  'invoice factoring companies',
  'merchant cash advance ISOs',
  'promotional products and trade show display companies',
  'property preservation companies',
  'vendor compliance service companies',
  'insurance agencies',
  'tax services',
  'medical spas',
  'dental clinics',
  'law firms',
  'home health agencies',
  'auto repair shops',
  'spanish-speaking businesses',
]

export const GOOGLE_MAPS_PROVIDER_LABELS: Record<string, string> = {
  auto: 'Auto',
  google: 'Google Places',
  outscraper: 'Outscraper Maps',
}

export const OFFER_PRIORITY: LeadOffer[] = [
  'DealVault Agreement & Milestone Records',
  'DealVault / Operator Accountability',
  'AI Receptionist Launch',
  'AI Appointment Booking System',
  'Website Upgrade Sprint',
  'Business Funding',
  'Business Credit Builder',
  'Gov Contract Readiness',
  'Real Estate Seller Lead',
  'Business Setup / Compliance Help',
  'Spanish Funding Assistance',
  'Grant/Funding Roadmap',
  'New Business Formation',
  'Credit Repair',
  'AI Receptionist',
  'Website Upgrade',
]

export const OUTREACH_UNSUBSCRIBE_NOTES = {
  sms: 'Reply STOP to opt out of future text outreach.',
  email: 'If this is not relevant, reply "opt out" and we will not contact you again.',
  facebook_dm: 'If you do not want follow-up messages, reply and we will close the conversation.',
  phone_script: 'If they are not interested, thank them, mark the lead closed, and do not continue follow-up.',
}
