export type MarketVerticalPreset = {
  id: string
  label: string
  description: string
  niches: string[]
}

export const marketVerticalPresets: MarketVerticalPreset[] = [
  {
    id: 'dealvault_workflows',
    label: 'DealVault Workflows',
    description: 'Smaller operator teams with milestone tracking, deliverable proof, split payouts, or vendor accountability pain.',
    niches: [
      'specialty trade subcontractors',
      'restoration and mitigation companies',
      'residential remodeling companies',
      'design-build remodelers',
      'construction draw and rehab contractors',
      'boutique property management companies',
      'staffing agencies',
      'contingent search firms',
      'marketing agencies with retainers',
      'managed service providers',
      'fractional cfo firms',
      'outsourced bookkeeping services',
      'event production companies',
      'sponsorship activation agencies',
      'permit expediting services',
      'owner representative firms',
      'freight brokerages',
      'truck dispatch services',
      'transaction coordinator services',
    ],
  },
  {
    id: 'dealvault_partner_ops',
    label: 'DealVault Partner Ops',
    description: 'Relationship-heavy businesses that depend on referral fees, lending coordination, partner splits, and fulfillment tracking.',
    niches: [
      'private lending brokers',
      'hard money brokers',
      'business funding referral partners',
      'equipment finance brokers',
      'invoice factoring companies',
      'merchant cash advance ISOs',
      'real estate joint venture operators',
      'public adjusters',
      'insurance restoration companies',
      'commercial cleaning companies',
      'commercial janitorial companies',
      'sign installation companies',
      'property preservation companies',
      'dumpster rental companies',
      'portable sanitation companies',
    ],
  },
  {
    id: 'local_services',
    label: 'Local Services',
    description: 'High-intent local operators that often need funding, SEO, or automation help.',
    niches: ['general contractors', 'roofers', 'restoration companies', 'HVAC contractors'],
  },
  {
    id: 'real_estate_money',
    label: 'Real Estate Money',
    description: 'Investor-adjacent businesses that fit funding, seller, and lender angles well.',
    niches: ['property management companies', 'real estate investment companies', 'hard money lenders', 'private lenders'],
  },
  {
    id: 'minority_growth',
    label: 'Minority Growth',
    description: 'Minority and underserved business angles with strong funding-readiness fit.',
    niches: ['Spanish-speaking contractors', 'Spanish-speaking tax services', 'Spanish-speaking insurance agencies', 'Spanish-speaking businesses'],
  },
  {
    id: 'professional_services',
    label: 'Professional Services',
    description: 'Cash-flowing service businesses that can convert into funding or automation clients.',
    niches: ['law firms', 'insurance agencies', 'tax preparers', 'marketing agencies'],
  },
  {
    id: 'health_beauty',
    label: 'Health + Beauty',
    description: 'Operators with strong monetization potential and recurring demand.',
    niches: ['clinics', 'med spas', 'dental clinics', 'chiropractors'],
  },
  {
    id: 'new_market_mix',
    label: 'New Market Mix',
    description: 'Balanced preset for testing a new city without overcommitting to one vertical.',
    niches: [
      'boutique property management companies',
      'specialty trade subcontractors',
      'business funding referral partners',
      'staffing agencies',
    ],
  },
  {
    id: 'revenue_high_fit_services',
    label: 'Revenue High-Fit Services',
    description: 'Higher-ticket, relationship-heavy service businesses that are more likely to need DealVault records, AI receptionist, visibility, or funding prep.',
    niches: [
      'commercial restoration companies',
      'insurance restoration contractors',
      'construction project management companies',
      'commercial roofing companies',
      'residential remodeling companies',
      'design-build remodelers',
      'property management companies',
      'public adjusters',
      'private lenders',
      'hard money brokers',
      'business funding brokers',
      'equipment finance brokers',
      'invoice factoring companies',
      'staffing agencies',
      'recruiting agencies',
      'marketing agencies with retainers',
      'commercial cleaning companies',
      'sign installation companies',
      'permit expediting services',
      'owner representative firms',
    ],
  },
  {
    id: 'weak_web_presence_services',
    label: 'Weak Web Presence Services',
    description: 'Local operators likely to need a better website, AI receptionist, booking path, or search visibility cleanup.',
    niches: [
      'med spas',
      'dental clinics',
      'chiropractors',
      'salons',
      'barbershops',
      'auto repair shops',
      'tax preparers',
      'insurance agencies',
      'roofing contractors',
      'HVAC contractors',
      'plumbing contractors',
      'cleaning companies',
      'landscaping companies',
      'general contractors',
      'home remodeling companies',
      'property management companies',
    ],
  },
]

export function findMarketPreset(id: string | null | undefined) {
  return marketVerticalPresets.find((preset) => preset.id === id) || null
}
