import type { BorrowerMatchInput, LenderCategory, LenderType } from '@/lib/lenders/types'

export const DEFAULT_LENDER_DISCOVERY_STATES = ['WI', 'IL', 'IN', 'MI', 'OH', 'GA', 'TX', 'FL', 'TN', 'NC', 'AZ', 'NV', 'MO']

export const DEFAULT_LENDER_DISCOVERY_MARKETS = [
  { city: 'Milwaukee', state: 'WI', metroArea: 'Milwaukee' },
  { city: 'Chicago', state: 'IL', metroArea: 'Chicago' },
  { city: 'Indianapolis', state: 'IN', metroArea: 'Indianapolis' },
  { city: 'Detroit', state: 'MI', metroArea: 'Detroit' },
  { city: 'Columbus', state: 'OH', metroArea: 'Columbus' },
  { city: 'Atlanta', state: 'GA', metroArea: 'Atlanta' },
  { city: 'Houston', state: 'TX', metroArea: 'Houston' },
  { city: 'Miami', state: 'FL', metroArea: 'Miami' },
  { city: 'Nashville', state: 'TN', metroArea: 'Nashville' },
  { city: 'Charlotte', state: 'NC', metroArea: 'Charlotte' },
  { city: 'Phoenix', state: 'AZ', metroArea: 'Phoenix' },
  { city: 'Las Vegas', state: 'NV', metroArea: 'Las Vegas' },
  { city: 'Kansas City', state: 'MO', metroArea: 'Kansas City' },
] as const

export const DEFAULT_LENDER_DISCOVERY_NICHES = [
  'credit union',
  'community bank',
  'mortgage lender',
  'commercial lender',
  'hard money lender',
  'fix and flip lender',
  'DSCR lender',
  'equipment financing service',
  'small business lender',
  'SBA lender',
  'truck financing',
  'restaurant financing',
  'contractor financing',
  'community development financial institution',
] as const

export const LENDER_CATEGORY_TO_TYPE: Record<LenderCategory, LenderType> = {
  conventional_mortgage: 'real_estate',
  dscr: 'real_estate',
  fix_and_flip: 'real_estate',
  bridge: 'real_estate',
  hard_money: 'real_estate',
  refinance: 'real_estate',
  brrrr_friendly: 'real_estate',
  portfolio_bank: 'real_estate',
  construction: 'real_estate',
  commercial: 'real_estate',
  sba_504_real_estate: 'real_estate',
  heloc: 'real_estate',
  private_lender: 'real_estate',
  creative_finance_partner: 'real_estate',
  startup_friendly: 'business',
  term_loan: 'business',
  line_of_credit: 'business',
  sba_7a: 'business',
  sba_microloan: 'business',
  revenue_based: 'business',
  invoice_factoring: 'business',
  equipment_finance: 'business',
  franchise_finance: 'business',
  trucking_finance: 'business',
  restaurant_finance: 'business',
  contractor_finance: 'business',
  cdfi: 'business',
  community_bank: 'business',
  credit_union_business: 'business',
  personal_loan: 'personal',
  debt_consolidation: 'personal',
  credit_union_personal: 'personal',
  secured_share_loan: 'personal',
  heloc_personal: 'personal',
  relationship_bank_line: 'personal',
  credit_builder_partner: 'personal',
  spanish_market: 'specialty',
  minority_business_program: 'specialty',
  women_business_program: 'specialty',
  immigrant_business_program: 'specialty',
  economic_development: 'specialty',
  grant_support_partner: 'specialty',
  nonprofit_microloan: 'specialty',
  medical_practice_finance: 'specialty',
  auto_repair_finance: 'specialty',
  logistics_finance: 'specialty',
}

export const CATEGORY_LABELS: Record<string, string> = {
  conventional_mortgage: 'Conventional Mortgage',
  dscr: 'DSCR',
  fix_and_flip: 'Fix and Flip',
  bridge: 'Bridge',
  hard_money: 'Hard Money',
  refinance: 'Refinance',
  brrrr_friendly: 'BRRRR Refinance',
  portfolio_bank: 'Portfolio Bank',
  construction: 'Construction',
  commercial: 'Commercial',
  sba_504_real_estate: 'SBA 504 Real Estate',
  heloc: 'HELOC',
  private_lender: 'Private Lender',
  creative_finance_partner: 'Creative Finance Partner',
  startup_friendly: 'Startup Friendly',
  term_loan: 'Term Loan',
  line_of_credit: 'Line of Credit',
  sba_7a: 'SBA 7(a)',
  sba_microloan: 'SBA Microloan',
  revenue_based: 'Revenue Based',
  invoice_factoring: 'Invoice Factoring',
  equipment_finance: 'Equipment Finance',
  franchise_finance: 'Franchise Finance',
  trucking_finance: 'Trucking Finance',
  restaurant_finance: 'Restaurant Finance',
  contractor_finance: 'Contractor Finance',
  cdfi: 'CDFI',
  community_bank: 'Community Bank',
  credit_union_business: 'Credit Union Business',
  personal_loan: 'Personal Loan',
  debt_consolidation: 'Debt Consolidation',
  credit_union_personal: 'Credit Union Personal',
  secured_share_loan: 'Secured Share Loan',
  heloc_personal: 'HELOC Personal',
  relationship_bank_line: 'Relationship Bank Line',
  credit_builder_partner: 'Credit Builder Partner',
  spanish_market: 'Spanish Market',
  minority_business_program: 'Minority Business Program',
  women_business_program: 'Women Business Program',
  immigrant_business_program: 'Immigrant Business Program',
  economic_development: 'Economic Development',
  grant_support_partner: 'Grant Support Partner',
  nonprofit_microloan: 'Nonprofit Microloan',
  medical_practice_finance: 'Medical Practice Finance',
  auto_repair_finance: 'Auto Repair Finance',
  logistics_finance: 'Logistics Finance',
}

export function suggestBorrowerDealType(input: BorrowerMatchInput) {
  if (input.dealType) return input.dealType
  const service = String(input.serviceType || '').toLowerCase()
  if (/real estate|seller|flip|brrrr|bridge|dscr/.test(service)) return 'real_estate'
  if (/startup|formation|compliance/.test(service)) return 'startup'
  if (/credit builder|credit repair|personal/.test(service)) return 'personal'
  return 'business'
}
