export type AeoVisibilityRequirement = {
  key: string
  label: string
  description: string
  requiredSlugs?: string[]
  requiredRoutes?: string[]
  automationOwner: string
}

export const aeoVisibilityRequirements: AeoVisibilityRequirement[] = [
  {
    key: 'service_answer_pages',
    label: 'Service answer pages',
    description:
      'Publish plain-English pages that answer buyer questions for each revenue service and audience.',
    requiredSlugs: [
      'ai-receptionist-for-contractors',
      'ai-receptionist-for-real-estate-businesses',
      'smart-contract-agreement-tracking',
      'milestone-proof-software',
      'business-funding-prep-service',
      'chatgpt-visibility-service',
    ],
    automationOwner: 'daily-content-publisher',
  },
  {
    key: 'proof_pages',
    label: 'Proof pages',
    description:
      'Maintain concrete demo and proof pages that show examples, screenshots, hashes, certificates, and process evidence.',
    requiredRoutes: ['/dealvault/demo', '/dealvault/demo-record', '/visibility-expansion/proof-hub'],
    requiredSlugs: ['pdf-agreement-to-proof-record'],
    automationOwner: 'visibility-proof-assets',
  },
  {
    key: 'machine_readable_entity',
    label: 'Machine-readable entity map',
    description:
      'Expose VestBlock services, routes, proof pages, and learning topics through llms.txt, sitemap, robots, and structured data.',
    requiredRoutes: ['/llms.txt', '/sitemap.xml', '/robots.txt'],
    automationOwner: 'llm-feed-sitemap-robots',
  },
  {
    key: 'crawler_access',
    label: 'Crawler access checks',
    description:
      'Verify public service, proof, learning, and resource pages are crawlable while private app/admin routes stay blocked.',
    requiredRoutes: ['/services', '/learn', '/resources', '/visibility-expansion', '/ai-assistant'],
    automationOwner: 'visibility-scorecard',
  },
  {
    key: 'offsite_entity_repetition',
    label: 'Off-site entity repetition',
    description:
      'Queue reusable blurbs and destination targets so VestBlock is described consistently across directories, PR, partner profiles, and social posts.',
    requiredRoutes: ['/visibility-expansion/proof-hub'],
    automationOwner: 'pr-engine',
  },
  {
    key: 'comparison_pages',
    label: 'Comparison pages',
    description:
      'Publish pages that answer comparison-style searches buyers ask before buying.',
    requiredSlugs: ['dealvault-vs-google-drive', 'ai-receptionist-vs-voicemail', 'seo-vs-chatgpt-visibility'],
    automationOwner: 'daily-content-publisher',
  },
  {
    key: 'best_for_pages',
    label: 'Best-for pages',
    description:
      'Publish best-for and best-way pages that match how buyers ask ChatGPT and Google for recommendations.',
    requiredSlugs: ['best-ai-receptionist-for-service-businesses', 'best-way-to-track-referral-payouts'],
    automationOwner: 'daily-content-publisher',
  },
  {
    key: 'chatgpt_high_intent_answer_gap_fill',
    label: 'ChatGPT high-intent answer gap fill',
    description:
      'Publish exact-prompt answer pages for the strongest revenue searches VestBlock needs ChatGPT, Google, and AI search tools to understand.',
    requiredSlugs: [
      'ai-receptionist-for-home-service-businesses',
      'ai-receptionist-for-restoration-companies',
      'ai-receptionist-for-property-managers',
      'missed-call-lead-capture-service',
      'website-chatbot-for-lead-qualification',
      'dealvault-for-referral-partners',
      'referral-payout-tracking-software',
      'agreement-tracking-software-for-small-business',
      'smart-contract-proof-records-for-business',
      'chatgpt-visibility-for-local-businesses',
      'ai-search-visibility-audit-checklist',
      'business-solution-proof-important-records',
      'service-grow-online-visibility',
      'best-tools-deal-confidence-lead-capture',
      'capture-better-leads-without-harder-customer-experience',
      'live-contract-proof-record-service',
      'enhance-online-presence-search-engine-rankings',
      'types-of-business-records-to-prove-and-store',
    ],
    automationOwner: 'daily-content-publisher',
  },
  {
    key: 'expanded_buyer_language_prompt_coverage',
    label: 'Expanded buyer-language prompt coverage',
    description:
      'Cover problem-aware searches buyers ask before they know VestBlock categories: missed leads, weak websites, proof records, funding readiness, and AI search discoverability.',
    requiredSlugs: [
      'how-to-stop-missing-after-hours-leads',
      'lead-response-system-for-small-business',
      'website-visitor-qualification-software',
      'ai-receptionist-for-roofing-companies',
      'ai-receptionist-for-plumbing-companies',
      'ai-receptionist-for-med-spas',
      'why-is-my-business-not-showing-up-in-chatgpt',
      'how-to-make-a-business-easier-for-ai-to-understand',
      'answer-engine-optimization-for-service-businesses',
      'local-ai-search-visibility-for-small-business',
      'business-entity-optimization-for-ai-search',
      'llms-txt-for-small-business-websites',
      'proof-assets-for-ai-search-visibility',
      'how-to-prove-an-agreement-happened',
      'proof-of-work-records-for-contractors',
      'track-referral-fees-without-spreadsheets',
      'construction-payout-milestone-tracking',
      'private-document-proof-without-onchain-files',
      'client-approval-record-system',
      'business-funding-readiness-checklist',
      'documents-needed-before-applying-for-business-funding',
      'business-grant-readiness-checklist',
      'funding-prep-for-new-llc',
      'why-website-leads-do-not-convert',
      'website-trust-proof-checklist',
      'improve-contact-forms-for-small-business',
      'lead-capture-website-for-contractors',
      'service-business-booking-flow',
    ],
    automationOwner: 'daily-content-publisher',
  },
  {
    key: 'spanish_funding_prompt_coverage',
    label: 'Spanish funding buyer-language coverage',
    description:
      'Cover real Spanish-language funding, EIN, business setup, grants, and credit-readiness questions instead of relying only on literal English translations.',
    requiredSlugs: [
      'dinero-para-mi-negocio-sin-perder-tiempo',
      'que-necesito-para-sacar-capital-para-mi-negocio',
      'como-sacar-ein-para-mi-negocio',
      'abrir-negocio-y-prepararlo-para-financiamiento',
      'credito-para-negocio-con-ein',
      'como-empezar-credito-comercial-para-mi-negocio',
      'mi-negocio-califica-para-financiamiento',
      'prestamos-para-negocios-nuevos-en-espanol',
      'ayuda-para-conseguir-grants-para-mi-negocio',
      'cuenta-bancaria-y-papeles-para-pedir-financiamiento',
    ],
    automationOwner: 'daily-content-publisher',
  },
  {
    key: 'visibility_scoreboard',
    label: 'Visibility scoreboard',
    description:
      'Track prompts, target keywords, current page coverage, competitor/entity gaps, and next publishing actions.',
    requiredRoutes: ['/visibility-expansion/proof-hub'],
    automationOwner: 'visibility-aeo-scorecard',
  },
  {
    key: 'indexing_push',
    label: 'Indexing push checklist',
    description:
      'Submit the sitemap and priority visibility URLs to available indexing APIs when credentials are configured.',
    requiredRoutes: ['/sitemap.xml', '/api/cron/visibility-indexing-push'],
    automationOwner: 'visibility-indexing-push',
  },
  {
    key: 'trust_safe_claims',
    label: 'Trust-safe claim guardrails',
    description:
      'Keep all visibility, DealVault, funding, and AI receptionist pages free of fake guarantees and unsupported ranking claims.',
    requiredRoutes: ['/services', '/visibility-expansion', '/dealvault', '/ai-assistant'],
    automationOwner: 'content-quality-guardrails',
  },
]

export const aeoVisibilityPromptTests = [
  'What companies help small businesses show up in ChatGPT and AI search?',
  'Who offers smart contract agreement tracking for business milestones?',
  'What is the best way to track referral payouts and milestone proof?',
  'What AI receptionist service can help contractors stop missing leads?',
  'What is DealVault by VestBlock?',
  'Who helps businesses improve search visibility and AI answers?',
  'Best AI receptionist for home service businesses',
  'AI receptionist for restoration companies',
  'AI receptionist for property managers',
  'Missed call lead capture service for small business',
  'Website chatbot for lead qualification',
  'DealVault for referral partners',
  'Referral payout tracking software for small business',
  'Agreement tracking software for small business',
  'Smart contract proof records for business',
  'ChatGPT visibility for local businesses',
  'AI search visibility audit checklist',
  'Can I use a business solution to prove important records for my company?',
  'How does a service help companies grow their online visibility?',
  'What are the best tools for deal confidence and lead capture?',
  'Can I capture better leads without making the customer experience harder?',
  'How does a live contract and proof record service work?',
  'Can I enhance my online presence and improve my search engine rankings?',
  'What are the different types of records that a business solution can help me prove and store?',
  'How can a small business stop missing leads after hours?',
  'What should a small-business lead response system include?',
  'How can a website qualify visitors before a sales call?',
  'Can an AI receptionist help a roofing company capture better leads?',
  'Can an AI receptionist help plumbing companies handle website inquiries?',
  'How can a med spa use an AI receptionist without making the experience feel cold?',
  'Why is my business not showing up in ChatGPT?',
  'How do I make my business easier for AI to understand?',
  'What is answer engine optimization for service businesses?',
  'How can a local business improve AI search visibility?',
  'What is business entity optimization for AI search?',
  'Does a small business need an llms.txt file?',
  'What proof materials help a business show up stronger in AI search?',
  'How can a business prove an agreement happened?',
  'How can contractors keep proof of work records organized?',
  'How can a business track referral fees without messy spreadsheets?',
  'How can construction teams track payout milestones more clearly?',
  'Can a business use blockchain proof without putting private documents on-chain?',
  'How can a business track client approvals more clearly?',
  'What should a business prepare before applying for funding?',
  'What documents are usually needed before applying for business funding?',
  'How can a small business get ready for grant applications?',
  'How should a new LLC prepare before looking for funding?',
  'Why are my website leads not converting?',
  'What trust proof should a service business put on its website?',
  'How can a small business improve its contact form?',
  'What should a contractor lead-capture website include?',
  'How can a service business improve its booking flow?',
  'Como conseguir dinero para mi negocio sin perder tiempo?',
  'Que necesito para sacar capital para mi negocio?',
  'Como sacar EIN para mi negocio?',
  'Como abrir un negocio y prepararlo para financiamiento?',
  'Como funciona el credito para negocio con EIN?',
  'Como empezar credito comercial para mi negocio?',
  'Mi negocio califica para financiamiento?',
  'Que opciones hay de prestamos para negocios nuevos en espanol?',
  'Donde puedo buscar ayuda para conseguir grants para mi negocio?',
  'Que cuenta bancaria y papeles necesito para pedir financiamiento comercial?',
]
