import type { FundingProfile } from '@/lib/funding/types';

export const vestblockFundingMockProfiles: Record<string, FundingProfile> = {
  strongBusinessUser: {
    mode: 'business',
    funding_goal_amount: 75000,
    funding_goal_reason: 'Inventory, ad spend, and short-term working capital.',
    fico_estimate: 748,
    income_range: '$12,000-$20,000/mo',
    monthly_debt_payments: 1800,
    credit_utilization: 12,
    recent_inquiries_count: 2,
    new_accounts_24_months: 1,
    has_llc: true,
    business_name: 'Summit Trade Group LLC',
    business_start_date: '2021-03-15',
    business_revenue_range: '$100K-$250K',
    business_industry: 'E-commerce',
    ein_available: true,
  },
  weakPersonalCreditUser: {
    mode: 'personal',
    funding_goal_amount: 12000,
    funding_goal_reason: 'Debt reshuffle and emergency reserve coverage.',
    fico_estimate: 612,
    income_range: '$4,000-$6,000/mo',
    monthly_debt_payments: 1450,
    credit_utilization: 68,
    recent_inquiries_count: 7,
    new_accounts_24_months: 5,
    has_llc: false,
    business_name: '',
    business_revenue_range: '$0-$25K',
    business_industry: '',
    ein_available: false,
  },
  hybridUser: {
    mode: 'hybrid',
    funding_goal_amount: 50000,
    funding_goal_reason: 'Launch services, equipment, and reserve runway.',
    fico_estimate: 708,
    income_range: '$8,000-$12,000/mo',
    monthly_debt_payments: 1100,
    credit_utilization: 24,
    recent_inquiries_count: 3,
    new_accounts_24_months: 2,
    has_llc: true,
    business_name: 'Northline Studio LLC',
    business_start_date: '2024-04-02',
    business_revenue_range: '$25K-$50K',
    business_industry: 'Creative agency',
    ein_available: true,
  },
  repairFirstHighUtilizationUser: {
    mode: 'business',
    funding_goal_amount: 30000,
    funding_goal_reason: 'Working capital and equipment.',
    fico_estimate: 635,
    income_range: '$6,000-$8,000/mo',
    monthly_debt_payments: 1650,
    credit_utilization: 82,
    recent_inquiries_count: 6,
    new_accounts_24_months: 4,
    has_llc: false,
    business_name: 'Westfield Repairs',
    business_start_date: '2025-01-10',
    business_revenue_range: '$0-$25K',
    business_industry: 'Repair services',
    ein_available: false,
  },
};
